modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/SlimeKnights/TinkersConstruct/issues"
logoFile="logo.png"
license="MIT"

[[mods]]
    modId="tconstruct"
    version="${version}"
    displayName="Tinkers' Construct"
    authors="Slime Knights"
    description='''
A little of this, a little of that, a lot of tinkering, and a lot of tools
    '''
    displayURL="https://www.curseforge.com/minecraft/mc-mods/tinkers-construct"
    
[[dependencies.tconstruct]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tconstruct]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tconstruct]]
    modId="mantle"
    mandatory=true
    versionRange="${mantle_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tconstruct]]
    modId="jei"
    mandatory=false
    versionRange="${jei_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tconstruct]]
    modId="jsonthings"
    mandatory=false
    versionRange="${json_things_range}"
    ordering="NONE"
    side="BOTH"
