blank_issues_enabled: false
contact_links:
 - name: SlimeKnights Discord
   url: https://discord.gg/njGrvuh
   about: Join our discord to discuss new features or to discuss behavior that may not be a bug.
